## BATCH SIZE 16 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 16 --test-bs 16 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 32 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 32 --test-bs 32 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 64 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 64 --test-bs 64 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 128 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 128 --test-bs 128 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 256 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 256 --test-bs 256 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 512 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 512 --test-bs 512 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

## BATCH SIZE 1024 ##
python ./code/CKA.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//CKA_mixup_alpha_16.err
python ./code/CKA.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/ --early-stopping --mixup-CKA --mixup-alpha 16.0 --not-input --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics/CKA_mixup_alpha_16.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//CKA_mixup_alpha_16.err

