## BATCH SIZE 16 ##
echo "Running BATCH SIZE 16"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 32 ##
echo "Running BATCH SIZE 32"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 64 ##
echo "Running BATCH SIZE 64"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 128 ##
echo "Running BATCH SIZE 128"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 256 ##
echo "Running BATCH SIZE 256"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 512 ##
echo "Running BATCH SIZE 512"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

## BATCH SIZE 1024 ##
echo "Running BATCH SIZE 1024"
python ./code/loss_acc.py --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//loss_acc_uniform0.1.err
python ./code/loss_acc.py --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT/uniform  --train-or-test test --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/ --noise --noise-type uniform --noise-magnitude 0.1 --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics/loss_acc_uniform0.1.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//loss_acc_uniform0.1.err

