## BATCH SIZE 16 ##
echo "****** Running BATCH SIZE 16 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline/hessian.err

## BATCH SIZE 32 ##
echo "****** Running BATCH SIZE 32 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline/hessian.err

# ## BATCH SIZE 64 ##
echo "****** Running BATCH SIZE 64 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline/hessian.err

## BATCH SIZE 128 ##
echo "****** Running BATCH SIZE 128 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline/hessian.err

## BATCH SIZE 256 ##
echo "****** Running BATCH SIZE 256 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline/hessian.err

## BATCH SIZE 512 ##
echo "****** Running BATCH SIZE 512 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline/hessian.err

## BATCH SIZE 1024 ##
echo "****** Running BATCH SIZE 1024 ******"
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline/hessian.err
python ../common/measure_hessian.py --training-type normal --experiment-name baseline --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/baseline --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline/hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline/hessian.err
