## BATCH SIZE 16 ##
echo "Running BATCH SIZE 16"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 32 ##
echo "Running BATCH SIZE 32"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 64 ##
echo "Running BATCH SIZE 64"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 128 ##
echo "Running BATCH SIZE 128"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 256 ##
echo "Running BATCH SIZE 256"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 512 ##
echo "Running BATCH SIZE 512"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/ECON_11b/metrics/baseline//neural_eff.err

## BATCH SIZE 1024 ##
echo "Running BATCH SIZE 1024"
python ../common/neural_eff.py --arch ECON_6b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_6b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_7b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_8b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_9b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_10b/metrics/baseline//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --experiment-name baseline --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/baseline --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/ECON_11b/metrics/baseline//neural_eff.err
