## LEARNING RATE 0.1 ##
echo "Running LEARNING RATE 0.1"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.05 ##
echo "Running LEARNING RATE 0.05"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.025 ##
echo "Running LEARNING RATE 0.025"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.0125 ##
echo "Running LEARNING RATE 0.0125"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.00625 ##
echo "Running LEARNING RATE 0.00625"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.003125 ##
echo "Running LEARNING RATE 0.003125"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics/small/gradient.err >&2) 
## LEARNING RATE 0.0015625 ##
echo "Running LEARNING RATE 0.0015625"
python ../common/gradient.py --early-stopping --arch ECON_6b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_7b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_8b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_9b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_10b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics/small/gradient.err >&2) 
python ../common/gradient.py --early-stopping --arch ECON_11b --experiment-name small --train-or-test test --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/small --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics/small/gradient.pkl > >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics/small/gradient.log) 2> >(tee -a ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics/small/gradient.err >&2) 
