## BATCH SIZE 16 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 32 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 64 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 128 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 256 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 512 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics//fgsm.err

## BATCH SIZE 1024 ##
python ../common/fgsm.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics//fgsm.err
python ../common/fgsm.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics/fgsm_0.01.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics//fgsm.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics//fgsm.err

