## BATCH SIZE 16 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_32b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//hessian_test.err 

## BATCH SIZE 32 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_32b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//hessian_test.err 

## BATCH SIZE 64 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_32b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//hessian_test.err 

## BATCH SIZE 128 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_32b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//hessian_test.err 

## BATCH SIZE 256 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_32b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//hessian_test.err 

## BATCH SIZE 512 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_32b/metrics//hessian_test.err 

## BATCH SIZE 1024 ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_32b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_32b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_32b/metrics//hessian_test.err 

## 32 BIT ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//hessian_test.err 
## 7 BIT ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//hessian_test.err 
## 8 BIT ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//hessian_test.err 
## 9 BIT ##
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//hessian_test.err 
python ./code/measure_hessian.py --training-type bs_decay --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics/hessian_test.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//hessian_test.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//hessian_test.err 
