## BATCH SIZE 16 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_16/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_16/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 32 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_32/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_32/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 64 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_64/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_64/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 128 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_128/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_128/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 256 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_256/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_256/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 512 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_512/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_512/normal/JT_32b/metrics//hessian.err 

## BATCH SIZE 1024 ##
python ./code/measure_hessian.py --training-type normal --arch JT_6b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_6b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_7b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_7b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_8b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_8b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_9b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_9b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_10b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_10b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_11b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_11b/metrics//hessian.err 
python ./code/measure_hessian.py --training-type normal --arch JT_32b --data-subset --subset 1.0 --data-path ../../data/JT  --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_32b/ --early-stopping --result-location ../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_32b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_32b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/bs_1024/normal/JT_32b/metrics//hessian.err 
