## BATCH SIZE 16 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 16 --test-bs 16 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_16/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 32 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 32 --test-bs 32 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_32/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 64 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 64 --test-bs 64 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_64/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 128 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 128 --test-bs 128 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_128/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 256 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 256 --test-bs 256 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_256/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 512 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_512/bs_decay/JT_11b/metrics//neural_eff.err

## BATCH SIZE 1024 ##
python ./code/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_6b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_7b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_8b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_9b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_10b/metrics//neural_eff.err
python ./code/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT --train-bs 1024 --test-bs 1024 --checkpoint-folder ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/bs_1024/bs_decay/JT_11b/metrics//neural_eff.err

