## LEARNING RATE 0.1 ##
echo "Running LEARNING RATE 0.1"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.05 ##
echo "Running LEARNING RATE 0.05"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.025 ##
echo "Running LEARNING RATE 0.025"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.0125 ##
echo "Running LEARNING RATE 0.0125"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.00625 ##
echo "Running LEARNING RATE 0.00625"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.003125 ##
echo "Running LEARNING RATE 0.003125"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/lr_decay/JT_11b/metrics/neural_eff.err

## LEARNING RATE 0.0015625 ##
echo "Running LEARNING RATE 0.0015625"
python ../common/neural_eff.py --arch JT_6b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_6b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_6b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_6b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_7b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_7b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_7b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_7b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_8b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_8b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_8b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_8b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_9b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_9b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_9b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_9b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_10b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_10b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_10b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_10b/metrics/neural_eff.err
python ../common/neural_eff.py --arch JT_11b --early-stopping --data-path ../../data/JT/ --train-bs 512 --test-bs 512 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_11b/ --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_11b/metrics/neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/lr_decay/JT_11b/metrics/neural_eff.err

