## LEARNING RATE 0.1 ##
echo "****** Running LEARNING RATE 0.1 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics//hessian.err

## LEARNING RATE 0.05 ##
echo "****** Running LEARNING RATE 0.05 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics//hessian.err

# ## LEARNING RATE 0.025 ##
echo "****** Running LEARNING RATE 0.025 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics//hessian.err

## LEARNING RATE 0.0125 ##
echo "****** Running LEARNING RATE 0.0125 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics//hessian.err

## LEARNING RATE 0.00625 ##
echo "****** Running LEARNING RATE 0.00625 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics//hessian.err

## LEARNING RATE 0.003125 ##
echo "****** Running LEARNING RATE 0.003125 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics//hessian.err

## LEARNING RATE 0.0015625 ##
echo "****** Running LEARNING RATE 0.0015625 ******"
python ../common/measure_hessian.py --training-type normal --arch ECON_6b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_7b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_8b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_9b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_10b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics//hessian.err
python ../common/measure_hessian.py --training-type normal --arch ECON_11b --data-subset --subset 1.0 --train-bs 2000 --test-bs 2000 --train-or-test test --hessian-batch-size 2000 --mini-hessian-batch-size 2000 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/autoencoder --early-stopping --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics/hessian.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics//hessian.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics//hessian.err
