## LEARNING RATE 0.1 ##
echo "Running LEARNING RATE 0.1"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.1/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.05 ##
echo "Running LEARNING RATE 0.05"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.05/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.025 ##
echo "Running LEARNING RATE 0.025"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.025/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.0125 ##
echo "Running LEARNING RATE 0.0125"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0125/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.00625 ##
echo "Running LEARNING RATE 0.00625"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.00625/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.003125 ##
echo "Running LEARNING RATE 0.003125"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.003125/normal/ECON_11b/metrics//neural_eff.err

## LEARNING RATE 0.0015625 ##
echo "Running LEARNING RATE 0.0015625"
python ../common/neural_eff.py --arch ECON_6b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_6b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_7b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_7b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_8b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_8b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_9b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_9b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_10b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_10b/metrics//neural_eff.err
python ../common/neural_eff.py --arch ECON_11b --early-stopping --data-path ../../data/ECON/Elegun --train-bs 500 --test-bs 500 --checkpoint-folder ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/autoencoder --result-location ../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics/neural_eff.pkl 1>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics//neural_eff.log 2>../checkpoint/different_knobs_subset_10/lr_0.0015625/normal/ECON_11b/metrics//neural_eff.err

